[tool.poetry]
name = "repl_nix_ljflisp3"
version = "0.1.0"
description = ""
authors = ["ljf7 <<>>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
